### ISSUE TITLE
NTR: Request for L05 Pinger sub-bottom profilers

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/L05#10]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Pinger sub-bottom profilers <p><b>Definition</b><p> Marine seismic sources that send sound pulses into the sub-sea floor sediments. The sound pulses bounce off the sea floor and subsequent buried sediment layers according to differences in their acoustic impedance (hardness) and in turn, their density. Pingers are single channel, high frequency systems that typically operate between 2 kHz to 20 kHz.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.ga.gov.au/scientific-topics/marine/survey-techniques/sonar/shallow-water-sub-bottom-data<p> <b>Synonym or acronym (AltLabel)</b><p> PING<p><b>Mapping to other terminologies </b><p> http://vocab.nerc.ac.uk/collection/L21/current/ICAT07/<p>

**Comment by louatbodc** [comment]
Please could comments be posted by the 24th June.

Many thanks
Lou (NVS-vocabs team)
