### ISSUE TITLE
NTR: Request for L05 Argo Float

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/L05#21]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Argo Float <p><b>Definition</b><p> A profiling float with a suite of sensors used in the international Argo program. The floats drift with the ocean currents and move up and down between the surface and depth. The data and the float position are relayed to satellites and then on to receiving stations on shore. New float designs have allowed floats to profile deeper, to work in ice-covered regions and to measure other ocean properties beyond the basic salinity temperature and pressure but all must maintain common and high standards set by the international steering team.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://argo.ucsd.edu/about/<p> <b>ORCID</b><p> 0000-0002-3030-5177<p>

**Comment by SLBlakeman** [comment]
This term is better suited to the B76 vocabulary, BODC platforms, which are terms used to describe designs or versions of platforms. There is an existing B76 for Unspecified Argo float https://vocab.nerc.ac.uk/collection/B76/current/B7600006/. 

Any sensors associated to the Argo float would then have individual L22 terms and be associated to specific L05 terms that describe the instrument, e.g. Sea-Bird SBE 43 Dissolved Oxygen Sensor is an L22 term https://vocab.nerc.ac.uk/collection/L22/current/TOOL0036/ which is linked to the L05 term dissolved gas sensors https://vocab.nerc.ac.uk/collection/L05/current/351/
