### ISSUE TITLE
Need a new term for DIC Coulometer coupled with SOMMA (BODCNVS-1765)

### ISSUE THREAD

**Issue by lqjiang** [nvs-vocabs/L05#23]
This instrument is described in this dataset:
https://www.ncei.noaa.gov/data/oceans/ncei/ocads/metadata/0123467.html

"Two systems consisting of a coulometer (UIC Inc.) coupled with a Dissolved Inorganic Carbon Extractor (DICE) inlet system. DICE was developed by Esa Peltola and Denis Pierrot of NOAA/AOML and Dana Greeley of NOAA/PMEL to modernize a carbon extractor called SOMMA (Johnson et al. 1985, 1987, 1993, and 1999; Johnson 1992)"

Citations:

Dickson, A.G., C.L. Sabine, and J.R. Christian (eds.). 2007. Guide to best practices for ocean CO2 measurements. PICES Special Publication 3, 191 pp. Johnson, K.M., A.E. King, and J. McN. Sieburth. 1985. Coulometric DIC analyses for marine studies: An introduction. Mar. Chem., 16, 61-82. 

Johnson, K.M., P.J. Williams, L. Brandstrom, and J. McN. Sieburth. 1987. Coulometric total carbon analysis for marine studies: Automation and calibration. Mar. Chem., 21, 117-133. 

Johnson, K.M. 1992. Operator's manual: Single operator multiparameter metabolic analyzer (SOMMA) for total carbon dioxide (CT) with coulometric detection. Brookhaven National Laboratory, Brookhaven, N.Y., 70 pp. 

Johnson, K.M., K.D. Wills, D.B. Butler, W.K. Johnson, and C.S. Wong. 1993. Coulometric total carbon dioxide analysis for marine studies: Maximizing the performance of an automated continuous gas extraction system and coulometric detector. Mar. Chem., 44, 167-189. 

Johnson, K.M., Kortzinger, A.; Mintrop, L.; Duinker, J.C.; and Wallace, D.W.R. 1999. Coulometric total carbon dioxide analysis for marine studies: Measurement and internal consistency of underway surface TCO2 concentrations. Marine Chemistry 67(1):123-144.

Thanks,

Liqing

**Comment by danibodc** [comment]
Hi @lqjiang, many thanks for your request.

For these types of instruments that use coulometric titration, a suitable L05 category to use would be:

titrators: http://vocab.nerc.ac.uk/collection/L05/current/LAB12/

We would not want to create a more specific L05 category that describes the types of measurement e.g DIC in this case. If you would like this instrument to be added to the L22 collection, please put in a request at: https://github.com/nvs-vocabs/L22/issues
