### ISSUE TITLE
NTR: sample dividers

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/L05#25]
### Term name (PrefLabel)
sample dividers

### Definition
A device used to subdivide material samples into two or more smaller portions.

### Sources/references
n/a

### Synonym or acronym (AltLabel)
sample splitters

### Mapping to external terminologies
n/a
### ORCID
0000-0002-1711-6478

**Comment by roy-lowry** [comment]
We used to call these 'sample splitters'. Might be worth including that in the description to provide a search target.

**Comment by Osanna123** [comment]
I agree with Roy about adding 'sample splitters' as a synonym. 
Also, I'd suggest to edit the definition a bit to: 'A device used to subdivide material samples into two or more representative portions.'

**Comment by roswri** [comment]
Thanks both for the suggestions, new code created:
397 - sample dividers (http://vocab.nerc.ac.uk/collection/L05/current/397/)
AltLabel=sample splitters	
Description: A device used to subdivide material samples into two or more representative portions.
