### ISSUE TITLE
NTR: New L05 request - acoustic scintillator [BODCNVS-2060]

### ISSUE THREAD

**Issue by vpaba** [nvs-vocabs/L05#30]
### Term name (PrefLabel)
acoustic scintillator
### Definition
instruments that measure flow and turbulence characteristics in oceanographic settings through acoustic scattering
### Sources/references
can provide internal design document

### Synonym or acronym (AltLabel)
Cabled Observatory Reciprocal Acoustic Scintillation, CORAS
### Mapping to external terminologies
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]
### ORCID
[Enter your ORCID if desired]

**Comment by JordanAthertonNOC** [comment]
One new L22 term created:

Cabled Observatory Reciprocal Acoustic Scintillation System (CORAS) (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2023/)
