### ISSUE TITLE
NTR: Request for sediment suction samplers [BODCNVS-324]

### ISSUE THREAD

**Issue by louatbodc** [nvs-vocabs/L05#6]
### Term name (PrefLabel)
sediment suction samplers
### Definition
Devices that collect samples of surface sediment using suction. The mechanism of suction can be accomplished by either vacuum, by pressure difference between the air inside the sampler and surrounding water, by pumping water directly into the sampler or by under pressure air to elevate the sediment inside the sampler. Devices are typically diver- or remotely-operated.
### Sources/references
Requesting new term as part of handling a request from DASSH (UK). The term is requested to cover a mechanism of sampling that is different to sediment grabs.
### Synonym or acronym (AltLabel)
[Only use if the new device category has known synonyms or acronyms]
### Mapping to external terminologies
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]
### ORCID
[Enter your ORCID if desired]

**Comment by neil-ices-dk** [comment]
Sounds fine, one ambiguity in the definition around the use of 'surface' assuming this means bottom or sediment layer surface.

**Comment by louatbodc** [comment]
Hi Neil

How does this sound?

Definition

Devices that collect samples from the sediment layer surface using suction. The mechanism of suction can be accomplished by either vacuum, by pressure difference between the air inside the sampler and surrounding water, by pumping water directly into the sampler or by under pressure air to elevate the sediment inside the sampler. Devices are typically diver- or remotely-operated.

**Comment by neil-ices-dk** [comment]
Sounds good Louise 👍

**Comment by louatbodc** [comment]
New term created. Please note - it may talk uptimes to 24 hours for the term to appear on the NVS.

sediment suction samplers
http://vocab.nerc.ac.uk/collection/L05/current/391/
