### ISSUE TITLE
Proposal to broaden L05 term '311' - 'cameras'

### ISSUE THREAD

**Issue by louatbodc** [nvs-vocabs/L05#9]
Dear colleagues

We wish to propose the following changes to L05 (classification) terms related to cameras. The existing L05 terms for cameras (as shown below) has led to some confusion due to their specificity, particularly term '311' - 'cameras', which actually describes aerial and satellite cameras (as opposed to underwater and laboratory cameras) rather than a generic term which the preferred label 'cameras' may imply. Thus, this term may have been used incorrectly.

http://vocab.nerc.ac.uk/collection/L05/current/180/ - underwater cameras
http://vocab.nerc.ac.uk/collection/L05/current/311/ - cameras
http://vocab.nerc.ac.uk/collection/L05/current/LAB41/ - laboratory cameras

To resolve the issue, allowing easier administration and avoiding the creation of numerous terms to cover all future cases, we would like to propose using one term for cameras by broadening the term '311' to cover all cameras as follows:

CODE: 311
PREFLABEL: cameras
DESRIPTION: 
All types of photographic equipment used to record visual images. Includes stills, video, film and digital systems.

Thus, we would also like to deprecate the following terms:

http://vocab.nerc.ac.uk/collection/L05/current/180/ - underwater cameras
http://vocab.nerc.ac.uk/collection/L05/current/LAB41/ - laboratory cameras

We will ensure that all L22 terms that are semantically linked to deprecated L05 terms are reassigned to the broader 'cameras' (311) concept.

Please could all responses be made by the Monday the 15th June.

Many thanks

**Comment by danibodc** [comment]
The following L05 terms have now been deprecated:
http://vocab.nerc.ac.uk/collection/L05/current/180/ - underwater cameras
http://vocab.nerc.ac.uk/collection/L05/current/LAB41/ - laboratory cameras

All L22 terms that were semantically linked to the above L05 terms have been reassigned to the broader 'cameras' (311) concept.

The Description for L05 term 'cameras' (311) has been broadened to cover all future cases:
'All types of photographic equipment used to record visual images. Includes stills, video, film and digital systems.'

Many thanks
